In [11]:
import pandas as pd
from json import loads, dumps

# Definition of pressure categories (from ENCORE)

In [17]:
df = pd.read_excel('docs/SBTN-Materiality-Screening-Tool-v1.xlsx', 
                   engine='openpyxl', 
                   sheet_name="3 - Methodology", 
                   usecols="O:Q", 
                   skiprows=4, 
                   nrows=12).fillna(method='ffill')

In [18]:
df

,Nature-related issue area,Pressure category,Definition
0,Land/Water/Sea Use Change,Terrestrial ecosystem use,"Examples include area of agriculture by type, ..."
1,Land/Water/Sea Use Change,Freshwater ecosystem use,"Examples include area of wetland, ponds, lakes..."
2,Land/Water/Sea Use Change,Marine ecosystem use,"Examples include area of aquaculture by type, ..."
3,Resource exploitation,Water use,Examples include volume of groundwater consume...
4,Resource exploitation,Other resource use,"Examples include volume of mineral extracted, ..."
5,Climate Change,GHG emissions,Examples include volume of carbon dioxide (CO2...
6,Pollution,Non-GHG air pollutants,Examples include volume of fine particulate ma...
7,Pollution,Water pollutants,Examples include volume discharged to receivin...
8,Pollution,Soil pollutants,Examples include volume of waste matter discha...
9,Pollution,Solid waste,Examples include volume of waste by classifica...
10,Invasives and Other,Disturbances,Examples include decibels and duration of nois...
11,Invasives and Other,Biological alterations/interferences,Examples include number of non-native and inva...

In [14]:
df.groupby('Nature-related issue area').apply(lambda x: x)

                              Nature-related issue area  \
Nature-related issue area
Climate Change            5              Climate Change
Invasives and Other       10        Invasives and Other
                          11        Invasives and Other
Land/Water/Sea Use Change 0   Land/Water/Sea Use Change
                          1   Land/Water/Sea Use Change
                          2   Land/Water/Sea Use Change
Pollution                 6                   Pollution
                          7                   Pollution
                          8                   Pollution
                          9                   Pollution
Resource exploitation     3       Resource exploitation
                          4       Resource exploitation

                                                 Pressure category  \
Nature-related issue area
Climate Change            5                          GHG emissions
Invasives and Other       10                          Disturbances
                          11  Biological alterations/interferences
Land/Water/Sea Use Change 0              Terrestrial ecosystem use
                          1               Freshwater ecosystem use
                          2                   Marine ecosystem use
Pollution                 6                 Non-GHG air pollutants
                          7                       Water pollutants
                          8                        Soil pollutants
                          9                            Solid waste
Resource exploitation     3                              Water use
                          4                     Other resource use

                                                                     Definition
Nature-related issue area
Climate Change            5   Examples include volume of carbon dioxide (CO2...
Invasives and Other       10  Examples include decibels and duration of nois...
                          11  Examples include number of non-native and inva...
Land/Water/Sea Use Change 0   Examples include area of agriculture by type, ...
                          1   Examples include area of wetland, ponds, lakes...
                          2   Examples include area of aquaculture by type, ...
Pollution                 6   Examples include volume of fine particulate ma...
                          7   Examples include volume discharged to receivin...
                          8   Examples include volume of waste matter discha...
                          9   Examples include volume of waste by classifica...
Resource exploitation     3   Examples include volume of groundwater consume...
                          4   Examples include volume of mineral extracted, ...

In [19]:
result = df.to_json(orient="records")
parsed = loads(result)
with open('encore-pressure-categories.json', 'w') as outfile:
    outfile.write(dumps(parsed, indent=4))

# Full Materiality Dataset DO

In [15]:
df = pd.read_excel('docs/SBTN-Materiality-Screening-Tool-v1.xlsx', 
                   engine='openpyxl', 
                   sheet_name="7 - Full materiality dataset DO", 
                   usecols="A:L,N", 
                   keep_default_na=False,
)
df

,Row #,ID (from new dataset),isic_section,isic_division,isic_group,production_process,impact,score,meanscore,impactthresh,impactthreshisicgrp,materiality,avgmateriality
0,1,1,"Professional, scientific and technical activities",Legal and accounting activities,"Accounting, bookkeeping and auditing activitie...",Infrastructure holdings,non_ghg_airpollutants,6,6.0,7,6,0,1
1,2,2,"Professional, scientific and technical activities",Legal and accounting activities,"Accounting, bookkeeping and auditing activitie...",Infrastructure holdings,soil_pollutants,7,7.0,6,7,1,1
2,3,3,"Professional, scientific and technical activities",Legal and accounting activities,"Accounting, bookkeeping and auditing activitie...",Infrastructure holdings,solid_waste,6,6.0,7,6,0,1
3,4,4,"Professional, scientific and technical activities",Legal and accounting activities,"Accounting, bookkeeping and auditing activitie...",Infrastructure holdings,water_pollutants,7,7.0,7,7,1,1
4,5,5,"Professional, scientific and technical activities",Legal and accounting activities,"Accounting, bookkeeping and auditing activitie...",Infrastructure holdings,water_use,8,8.0,8,8,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1903,1903,Information and communication,Telecommunications,Wireless telecommunications activities,Telecommunication and wireless services,biological_alterations,8,8.0,6,6,1,1
1903,1904,1904,Information and communication,Telecommunications,Wireless telecommunications activities,Telecommunication and wireless services,soil_pollutants,4,4.0,6,7,0,0
1904,1905,1905,Information and communication,Telecommunications,Wireless telecommunications activities,Telecommunication and wireless services,solid_waste,6,6.0,7,6,0,1
1905,1906,1906,Information and communication,Telecommunications,Wireless telecommunications activities,Telecommunication and wireless services,terrestrial_use,7,7.0,8,8,0,0
1906,1907,1907,Information and communication,Telecommunications,Wireless telecommunications activities,Telecommunication and wireless services,water_pollutants,3,3.0,7,7,0,0

In [16]:
result = df.to_json(orient="records")
parsed = loads(result)
with open('full-materiality-dataset.json', 'w') as outfile:
    outfile.write(dumps(parsed, indent=4))